### ISSUE TITLE
how to get lua errors and stack trace?

### ISSUE THREAD

**Issue by Skaruts** [jangko/nimLUA#23]
When I introduce an error in my lua code, all I get is `attempt to call a string value` and the program stops.

Is there a way to get lua errors? 

(Or is this connected to not having access to `lua_error`? This is my first time trying to do this kind of thing, so I'm quite clueless.)

**Comment by jangko** [comment]
You can try to wrap your code in [xpcall](https://stackoverflow.com/questions/45788739/get-true-stack-trace-of-an-error-in-lua-pcall) from lua side.

Therefore no need to modify nimLUA

**Comment by Skaruts** [comment]
I'm a bit confused though. I managed to get a proper error and a traceback using xpcall on the lua side, but not on all the errors I tried to introduce: 
```lua
function fn()
	local x = 10
	print(x[1])         -- reliably throws an error and stack trace (trying to index a number, iirc)

	-- if uncommented, this should be an error
	-- foo    -- but it just throws "attempt to call a string value" and the program stops

	print "yellow world"
end

local status, err = xpcall(fn, debug.traceback)  -- if the 'foo' line is uncommented, this code doesn't seem to get executed
print(err)
```

What's also confusing me is this: I was following a C++ tutorial to learn more about this, and I replicated his program at the point where he purposely introduces an error, and lua gives him a descriptive error out of the box, but on my port of his code it just gives me that same `attempt to call a string value`. 

**Note: this isn't like a normal Nim error. I'm not omitting anything: there's no nim stack trace or anything else there, just a single stdout line saying `attempt to call a string value`.**

Maybe you can reproduce this with my code below, which is an exact port of his (hopefully I made no mistakes). There's no lua file involved, just a simple string.

```Nim
import nimLua

proc main() =
    var L = newNimLua()

    let r = L.doString("a = 7 + 11sdf")    # simple lua code here, with invalid code: '11sdf'
    if r == LUA_OK:
        L.getGlobal("a")
        if bool(L.isNumber(-1)):
            let a_in_nim = float(L.toNumber(-1))
            echo a_in_nim
    else:
        let err_msg = L.toString(-1)
        echo err_msg
    L.close()
main()

```

Here's the tutorial (it's a video though -- he introduces the error at the linked timestamp (8:12), and then runs the code): 
https://youtu.be/4l5HdmPoynw?t=492

**Comment by jangko** [comment]
seems like that youtube guy's lua c++ have a different behavior compared to lua c api.
but i already fixed it in #25, wait until i merged it.

**Comment by Skaruts** [comment]
He's using a C API though... Maybe this changed in newer versions of lua. 

Turns out this is actually a lua error, which strangely doesn't give a stack trace and is listed on [Lua For Beginners](https://en.wikipedia.org/wiki/Help:Lua_for_beginners) as one of several "Exasperating bugs"... Although it can happen for other reasons than the one that's mentioned there.

I'm still getting the same result with that last bit of code, though (despite your fix). This kinda sucks, as certain human mistakes in the code are not gonna be easy for the user to find. Unless I'm missing something. I'm gonna keep learning more about embedding lua.

Thanks.
